name: tal3thoom
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_offline: ^2.1.0
  device_preview:
    git:
      url: https://github.com/monkeydaichan/flutter_device_preview.git
      path: device_preview
  animate_do: ^2.1.0
  csc_picker: ^0.2.6
  calendar_date_picker2: ^0.1.7
  dio: ^4.0.0
  animated_bottom_navigation_bar: ^1.0.1
  curved_navigation_bar: ^1.0.3
  animated_text_kit: ^4.2.2
  legacy_buttons: ^0.0.1
  laravel_exception: ^0.0.4
  smooth_page_indicator:
  image_picker: ^0.8.5+3
  hijri_picker: ^3.0.0
  image_cropper: ^1.5.1
  flutter_rating_bar:
  expansion_card:
  webview_flutter: ^3.0.4
  expansion_tile_card:
  syncfusion_flutter_datepicker: ^20.1.59
  flutter_conditional_rendering: ^2.0.0
  carousel_slider: ^4.0.0
  convex_bottom_bar: ^3.1.0+1
  flutter_svg: ^1.0.0
  drawer_swipe: ^0.0.4
  readable: ^0.0.5
  flutter_spinkit: ^5.0.0
  fluttertoast: ^8.0.7
  awesome_dialog: ^2.1.2
  auto_size_text: ^3.0.0
  font_awesome_flutter: ^9.1.0

  flutter_datetime_picker:
    git:
      url: https://github.com/Realank/flutter_datetime_picker.git
      ref: master
  google_fonts: ^2.1.0
  get_storage: ^2.0.3

  logging: ^1.0.1
  pretty_dio_logger: ^1.1.1
  shared_preferences: ^2.0.11
  flutter_speed_dial: ^5.0.0+1
  cached_network_image: ^3.2.0
  html: ^0.15.0
  shimmer: ^2.0.0
  url_launcher: ^6.0.17
  get: ^4.6.1
  equatable: ^2.0.3
  flutter_bloc: ^7.3.3
  timezone: ^0.8.0
  rxdart: ^0.27.3
  edge_alerts: ^0.0.1
  easy_localization: ^3.0.0
  fancy_bottom_navigation: ^0.3.2
  country_list_pick: ^1.0.1+5
  intl_phone_field: ^3.1.0
  table_calendar: ^3.0.5
  intl: ^0.17.0
  timer_count_down: ^2.2.1
  date_time_picker: ^2.1.0
  file_picker: ^4.4.0
  flutter_tts: ^3.5.0
  flutter_form_builder: ^7.4.0
  open_file: ^3.2.1
  chewie: ^1.3.4
  video_player: ^2.2.7
  queen:
    git:
      url: https://github.com/maxzod/queen.git
      ref: f6cc4532a9690809d0ed3c5f1ae8717f1baf38d7
  provider: ^6.0.3
  country_picker: ^2.0.15



dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - lib/Resources/Translations/

  fonts:
    - family: NeoSans
      fonts:
        - asset: assets/fonts/NeoSansStd/alfont_com_NeoSansW23-Regular.ttf
    - family: NeoSansBold
      fonts:
        - asset: assets/fonts/NeoSansStd/alfont_com_AlFont_com_Neo-Sans-W23-m-1.ttf
    - family: Cairo
      fonts:
        - asset: assets/fonts/Cairo-Bold.ttf
    - family: DinBold
      fonts:
        - asset: assets/DIN Next LT Arabic/ArbFONTS-DINNextLTArabic-Bold-4.ttf
    - family: DinBold
      fonts:
        - asset: assets/DIN Next LT Arabic/ArbFONTS-DINNextLTArabic-Bold-4.ttf
    - family: DinLight
      fonts:
        - asset: assets/DIN Next LT Arabic/ArbFONTS-DINNEXTLTARABIC-LIGHT-2-2.ttf
    - family: DinMedium
      fonts:
        - asset: assets/DIN Next LT Arabic/ArbFONTS-DINNextLTArabic-Medium-4.ttf
    - family: DinReguler
      fonts:
        - asset: assets/DIN Next LT Arabic/ArbFONTS-DINNextLTArabic-Regular-4.ttf
    - family: DinUltraLight
      fonts:
        - asset: assets/DIN Next LT Arabic/ArbFONTS-DINNextLTArabic-UltraLight-4.ttf



































